### ISSUE TITLE
Account balance fluctuates wildly

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#139]
1. go to https://v2.rari.capital/
2. Connect metamask wallet that has RPST
3. look at account balance 

Expected: if you put in a stablecoin like USDC it should only be higher than the amount of the usdc you deposited
Actual: it could be higher or lower, seems to fluctuate by +/- $500

**Comment by TransmissionsDev** [comment]
Doesn't move too much for me but this is because stable and yield pool are multi asset pools and you are subject to each stablecoin's price movements inside the pool. More info here: https://www.notion.so/Capital-Allocation-Risks-f4bccf324a594f46b849e6358e0a2464

This loss is outweighed by our yield.

**Comment by jameselkins-mantl** [comment]
This ticket should not be closed as it is a UX bug. It must be communicated to the user that this behavior is expected and/or show the allocation of the stablecoin vs the price of the stablecoin so the user understands why their account balance does not reflect the amount of money they deposited.
