### ISSUE TITLE
Bug encountered connecting with metamask, cannot log in.

### ISSUE THREAD

**Issue by papermache** [Rari-Capital/rari-dApp#192]
![image](https://user-images.githubusercontent.com/2126012/99467734-016a7600-290d-11eb-84f1-c8def0d37229.png)

**Comment by TransmissionsDev** [comment]
Thanks for this report! We're aware of this issue and working on a fix as we speak. 

This issue is related to MStable and The Graph having changed their API, which the site relies on for most of the metrics on the site (apys, interest earned, etc), since this data is unavailable the site just reports the error as there is almost no data to be shown. 

We're working on a fix as we speak and should be out in ~20 minutes.

**Comment by TransmissionsDev** [comment]
Fixed thank you for the report! I very much appreciate you making a Github issue, it helps expedite everything!
